version: "3"

services:
  userservice:
    image: user_service:1.0.0
    ports:
      - "8000:8000"
  profile_service:
    image: "profile_service:1.0.0"
    environment:
      PGUSER: pspdfkit
      PGPASSWORD: password

    ports:
      - "8001:8001"
