version: "3"

services:
  userservice:
    image: sa30h/user_service:1.0.0
    ports:
      - "8000:8000"
  profile_service:
    image: sa30h/profile_service:1.0.0
    environment:
      USER_SERVICE_HOST: userservice
      USER_SERVICE_PORT: 8000

    ports:
      - "8001:8001"
